// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoommateFinder.Infrastructure.Data;

#nullable disable

namespace RoommateFinder.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006090017_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoommateFinder.Domain.Entities.Amenity", b =>
                {
                    b.Property<int>("AmenityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AmenityId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Amenities_Name");

                    b.ToTable("Amenities", (string)null);

                    b.HasData(
                        new
                        {
                            AmenityId = 1,
                            IsActive = true,
                            Name = "Điều hòa"
                        },
                        new
                        {
                            AmenityId = 2,
                            IsActive = true,
                            Name = "Wifi"
                        },
                        new
                        {
                            AmenityId = 3,
                            IsActive = true,
                            Name = "Máy giặt"
                        },
                        new
                        {
                            AmenityId = 4,
                            IsActive = true,
                            Name = "Tủ lạnh"
                        },
                        new
                        {
                            AmenityId = 5,
                            IsActive = true,
                            Name = "Chỗ để xe"
                        },
                        new
                        {
                            AmenityId = 6,
                            IsActive = true,
                            Name = "Nhà vệ sinh riêng"
                        },
                        new
                        {
                            AmenityId = 7,
                            IsActive = true,
                            Name = "Bếp nấu ăn"
                        },
                        new
                        {
                            AmenityId = 8,
                            IsActive = true,
                            Name = "Giờ giấc tự do"
                        },
                        new
                        {
                            AmenityId = 9,
                            IsActive = true,
                            Name = "Không chung chủ"
                        },
                        new
                        {
                            AmenityId = 10,
                            IsActive = true,
                            Name = "Ban công"
                        });
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AreaId");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.ConnectionRequest", b =>
                {
                    b.Property<long>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReceiverId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("pending");

                    b.HasKey("RequestId");

                    b.HasIndex("PostId", "SenderId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Request_SenderPost_Active")
                        .HasFilter("[Status] IN (N'pending', N'accepted')");

                    b.HasIndex("ReceiverId", "Status")
                        .HasDatabaseName("IX_Requests_Receiver");

                    b.HasIndex("SenderId", "Status")
                        .HasDatabaseName("IX_Requests_Sender");

                    b.ToTable("ConnectionRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_Request_NotSelf", "[SenderId] <> [ReceiverId]");

                            t.HasCheckConstraint("CK_Request_Status", "[Status] IN (N'pending', N'accepted', N'rejected', N'cancelled', N'expired')");
                        });
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.Conversation", b =>
                {
                    b.Property<long>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ConversationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<long>("User1Id")
                        .HasColumnType("bigint");

                    b.Property<long>("User2Id")
                        .HasColumnType("bigint");

                    b.HasKey("ConversationId");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Conversations_Request");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("Conversations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Conversation_NotSelf", "[User1Id] <> [User2Id]");
                        });
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.Landmark", b =>
                {
                    b.Property<int>("LandmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LandmarkId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("LandmarkId");

                    b.HasIndex("AreaId");

                    b.ToTable("Landmarks", null, t =>
                        {
                            t.HasCheckConstraint("CK_Landmark_Type", "[Type] IN (N'school', N'company', N'other')");
                        });
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("MessageId");

                    b.HasIndex("SenderId");

                    b.HasIndex("ConversationId", "SentAt")
                        .HasDatabaseName("IX_Messages_Conv");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("RelatedId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId", "IsRead", "CreatedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_Notif_User");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<long>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("TokenId");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("IX_PasswordResetTokens_TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens", (string)null);
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.Post", b =>
                {
                    b.Property<long>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PostId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CurrentOccupants")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExtendCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ModeratedBy")
                        .HasColumnType("bigint");

                    b.Property<int>("NeededOccupants")
                        .HasColumnType("int");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PreferredGender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12)
                        .HasColumnType("decimal(12,0)");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasDefaultValue("pending");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.HasIndex("AreaId");

                    b.HasIndex("ExpiredAt")
                        .HasDatabaseName("IX_Posts_ExpiredAt")
                        .HasFilter("[Status] = N'approved'");

                    b.HasIndex("ModeratedBy");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_Posts_User");

                    b.HasIndex("Status", "AreaId", "PostType", "Price")
                        .HasDatabaseName("IX_Posts_Search")
                        .HasFilter("[IsDeleted] = 0");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "AreaId", "PostType", "Price"), new[] { "PreferredGender", "NeededOccupants", "ExpiredAt", "Latitude", "Longitude" });

                    b.ToTable("Posts", null, t =>
                        {
                            t.HasCheckConstraint("CK_Post_CurrentOccupants", "[CurrentOccupants] >= 0");

                            t.HasCheckConstraint("CK_Post_NeededOccupants", "[NeededOccupants] >= 0");

                            t.HasCheckConstraint("CK_Post_PreferredGender", "[PreferredGender] IN (N'male', N'female', N'any')");

                            t.HasCheckConstraint("CK_Post_Price", "[Price] > 0");

                            t.HasCheckConstraint("CK_Post_Reject", "[Status] <> N'rejected' OR [RejectReason] IS NOT NULL");

                            t.HasCheckConstraint("CK_Post_Status", "[Status] IN (N'pending', N'approved', N'rejected', N'hidden', N'expired', N'closed')");

                            t.HasCheckConstraint("CK_Post_Type", "[PostType] IN (N'has_room', N'seeking')");
                        });
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.PostAmenity", b =>
                {
                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.HasKey("PostId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("PostAmenities", (string)null);
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.PostImage", b =>
                {
                    b.Property<long>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("PostId");

                    b.ToTable("PostImages", (string)null);
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.Report", b =>
                {
                    b.Property<long>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReportId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("HandledAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("HandledBy")
                        .HasColumnType("bigint");

                    b.Property<string>("HandledNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("PostId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReasonId")
                        .HasColumnType("int");

                    b.Property<long?>("ReportedUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReporterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("pending");

                    b.HasKey("ReportId");

                    b.HasIndex("HandledBy");

                    b.HasIndex("ReasonId");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("PostId", "CreatedAt")
                        .HasDatabaseName("IX_Reports_Post")
                        .HasFilter("[PostId] IS NOT NULL");

                    b.HasIndex("ReporterId", "PostId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Report_ReporterPost_Pending")
                        .HasFilter("[Status] = N'pending' AND [PostId] IS NOT NULL");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Reports_Status");

                    b.ToTable("Reports", null, t =>
                        {
                            t.HasCheckConstraint("CK_Report_NotSelf", "[ReportedUserId] IS NULL OR [ReportedUserId] <> [ReporterId]");

                            t.HasCheckConstraint("CK_Report_Status", "[Status] IN (N'pending', N'resolved', N'dismissed')");

                            t.HasCheckConstraint("CK_Report_Target", "([PostId] IS NOT NULL AND [ReportedUserId] IS NULL) OR ([PostId] IS NULL AND [ReportedUserId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.ReportReason", b =>
                {
                    b.Property<int>("ReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReasonId"));

                    b.Property<string>("AppliesTo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("both");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ReasonId");

                    b.ToTable("ReportReasons", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReportReason_AppliesTo", "[AppliesTo] IN (N'post', N'user', N'both')");
                        });

                    b.HasData(
                        new
                        {
                            ReasonId = 1,
                            AppliesTo = "post",
                            IsActive = true,
                            Name = "Tin đăng sai sự thật / tin ảo"
                        },
                        new
                        {
                            ReasonId = 2,
                            AppliesTo = "both",
                            IsActive = true,
                            Name = "Lừa đảo, yêu cầu chuyển tiền trước"
                        },
                        new
                        {
                            ReasonId = 3,
                            AppliesTo = "both",
                            IsActive = true,
                            Name = "Nội dung phản cảm, không phù hợp"
                        },
                        new
                        {
                            ReasonId = 4,
                            AppliesTo = "post",
                            IsActive = true,
                            Name = "Tin đăng trùng lặp"
                        },
                        new
                        {
                            ReasonId = 5,
                            AppliesTo = "user",
                            IsActive = true,
                            Name = "Quấy rối, ngôn từ xúc phạm"
                        },
                        new
                        {
                            ReasonId = 6,
                            AppliesTo = "user",
                            IsActive = true,
                            Name = "Giả mạo danh tính"
                        },
                        new
                        {
                            ReasonId = 7,
                            AppliesTo = "both",
                            IsActive = true,
                            Name = "Lý do khác"
                        });
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.Review", b =>
                {
                    b.Property<long>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<long>("RevieweeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReviewerId")
                        .HasColumnType("bigint");

                    b.HasKey("ReviewId");

                    b.HasIndex("RequestId");

                    b.HasIndex("RevieweeId")
                        .HasDatabaseName("IX_Reviews_Reviewee")
                        .HasFilter("[IsHidden] = 0");

                    b.HasIndex("ReviewerId", "RequestId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Review_ReviewerRequest");

                    b.ToTable("Reviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_Review_NotSelf", "[ReviewerId] <> [RevieweeId]");

                            t.HasCheckConstraint("CK_Review_Rating", "[Rating] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.SavedPost", b =>
                {
                    b.Property<long>("SavedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SavedId"));

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SavedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("SavedId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "PostId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Saved_UserPost");

                    b.ToTable("SavedPosts", (string)null);
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.SystemConfig", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ConfigKey");

                    b.ToTable("SystemConfigs", (string)null);

                    b.HasData(
                        new
                        {
                            ConfigKey = "POST_EXPIRE_DAYS",
                            ConfigValue = "30",
                            Description = "Số ngày hiển thị của một tin sau khi duyệt"
                        },
                        new
                        {
                            ConfigKey = "POST_MAX_EXTEND",
                            ConfigValue = "3",
                            Description = "Số lần gia hạn tối đa của một tin"
                        },
                        new
                        {
                            ConfigKey = "POST_MAX_PER_DAY",
                            ConfigValue = "3",
                            Description = "Số tin tối đa một người được đăng mỗi ngày (chống spam)"
                        },
                        new
                        {
                            ConfigKey = "POST_MAX_IMAGES",
                            ConfigValue = "10",
                            Description = "Số ảnh tối đa mỗi tin"
                        },
                        new
                        {
                            ConfigKey = "IMAGE_MAX_SIZE_MB",
                            ConfigValue = "5",
                            Description = "Dung lượng tối đa mỗi ảnh (MB)"
                        },
                        new
                        {
                            ConfigKey = "AUTO_HIDE_REPORT_COUNT",
                            ConfigValue = "5",
                            Description = "Số báo cáo để tự ẩn tin"
                        },
                        new
                        {
                            ConfigKey = "AUTO_HIDE_WINDOW_HOURS",
                            ConfigValue = "24",
                            Description = "Khoảng thời gian tính ngưỡng báo cáo (giờ)"
                        },
                        new
                        {
                            ConfigKey = "LOGIN_MAX_FAILED",
                            ConfigValue = "5",
                            Description = "Số lần đăng nhập sai liên tiếp trước khi khóa tạm"
                        },
                        new
                        {
                            ConfigKey = "LOGIN_LOCK_MINUTES",
                            ConfigValue = "15",
                            Description = "Thời gian khóa tạm sau khi đăng nhập sai (phút)"
                        },
                        new
                        {
                            ConfigKey = "RESET_TOKEN_MINUTES",
                            ConfigValue = "30",
                            Description = "Thời hạn mã đặt lại mật khẩu (phút)"
                        },
                        new
                        {
                            ConfigKey = "JWT_ACCESS_MINUTES",
                            ConfigValue = "120",
                            Description = "Thời hạn JWT (phút)"
                        },
                        new
                        {
                            ConfigKey = "REVIEW_MIN_DAYS",
                            ConfigValue = "7",
                            Description = "Số ngày tối thiểu sau khi chấp nhận kết nối mới được đánh giá"
                        },
                        new
                        {
                            ConfigKey = "SEARCH_MAX_DISTANCE_KM",
                            ConfigValue = "20",
                            Description = "Bán kính tối đa của bộ lọc khoảng cách (km)"
                        });
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("AvgRating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte?>("CleanlinessLevel")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("HasPet")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSmoker")
                        .HasColumnType("bit");

                    b.Property<int?>("LandmarkId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Occupation")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("user");

                    b.Property<string>("SchoolOrCompany")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SleepSchedule")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("active");

                    b.Property<DateTime?>("SuspendedUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Email");

                    b.HasIndex("LandmarkId");

                    b.HasIndex("Role", "Status")
                        .HasDatabaseName("IX_Users_Role_Status");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_Cleanliness", "[CleanlinessLevel] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_User_Gender", "[Gender] IN (N'male', N'female', N'other')");

                            t.HasCheckConstraint("CK_User_Occupation", "[Occupation] IN (N'student', N'worker')");

                            t.HasCheckConstraint("CK_User_Role", "[Role] IN (N'user', N'moderator', N'admin')");

                            t.HasCheckConstraint("CK_User_SleepSchedule", "[SleepSchedule] IN (N'early', N'late', N'flexible')");

                            t.HasCheckConstraint("CK_User_Status", "[Status] IN (N'active', N'suspended', N'banned')");

                            t.HasCheckConstraint("CK_User_Suspend", "[Status] <> N'suspended' OR [SuspendedUntil] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.ViolationHistory", b =>
                {
                    b.Property<long>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ViolationId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<long>("HandledBy")
                        .HasColumnType("bigint");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("PostId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReportId")
                        .HasColumnType("bigint");

                    b.Property<int?>("SuspendDays")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("ViolationId");

                    b.HasIndex("HandledBy");

                    b.HasIndex("PostId");

                    b.HasIndex("ReportId");

                    b.HasIndex("UserId");

                    b.ToTable("ViolationHistory", null, t =>
                        {
                            t.HasCheckConstraint("CK_Violation_Action", "[Action] IN (N'warning', N'hide_post', N'suspend_account', N'ban_account')");

                            t.HasCheckConstraint("CK_Violation_HidePost", "[Action] <> N'hide_post' OR [PostId] IS NOT NULL");

                            t.HasCheckConstraint("CK_Violation_Level", "[Level] IN (N'light', N'medium', N'severe')");

                            t.HasCheckConstraint("CK_Violation_Suspend", "[Action] <> N'suspend_account' OR [SuspendDays] IS NOT NULL");

                            t.HasCheckConstraint("CK_Violation_SuspendDays", "[SuspendDays] > 0");
                        });
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.ConnectionRequest", b =>
                {
                    b.HasOne("RoommateFinder.Domain.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoommateFinder.Domain.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoommateFinder.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("RoommateFinder.Domain.Entities.ConnectionRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoommateFinder.Domain.Entities.User", "User1")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoommateFinder.Domain.Entities.User", "User2")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.Landmark", b =>
                {
                    b.HasOne("RoommateFinder.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.Message", b =>
                {
                    b.HasOne("RoommateFinder.Domain.Entities.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoommateFinder.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.Notification", b =>
                {
                    b.HasOne("RoommateFinder.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("RoommateFinder.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.Post", b =>
                {
                    b.HasOne("RoommateFinder.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoommateFinder.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ModeratedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoommateFinder.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.PostAmenity", b =>
                {
                    b.HasOne("RoommateFinder.Domain.Entities.Amenity", "Amenity")
                        .WithMany()
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoommateFinder.Domain.Entities.Post", null)
                        .WithMany("PostAmenities")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.PostImage", b =>
                {
                    b.HasOne("RoommateFinder.Domain.Entities.Post", null)
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.Report", b =>
                {
                    b.HasOne("RoommateFinder.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("HandledBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoommateFinder.Domain.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoommateFinder.Domain.Entities.ReportReason", "Reason")
                        .WithMany()
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoommateFinder.Domain.Entities.User", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoommateFinder.Domain.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Reason");

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.Review", b =>
                {
                    b.HasOne("RoommateFinder.Domain.Entities.ConnectionRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoommateFinder.Domain.Entities.User", "Reviewee")
                        .WithMany()
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoommateFinder.Domain.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.SavedPost", b =>
                {
                    b.HasOne("RoommateFinder.Domain.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoommateFinder.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.User", b =>
                {
                    b.HasOne("RoommateFinder.Domain.Entities.Landmark", "Landmark")
                        .WithMany()
                        .HasForeignKey("LandmarkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Landmark");
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.ViolationHistory", b =>
                {
                    b.HasOne("RoommateFinder.Domain.Entities.User", "Handler")
                        .WithMany()
                        .HasForeignKey("HandledBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoommateFinder.Domain.Entities.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoommateFinder.Domain.Entities.Report", null)
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoommateFinder.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Handler");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoommateFinder.Domain.Entities.Post", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("PostAmenities");
                });
#pragma warning restore 612, 618
        }
    }
}
